# Generated by Django 5.1.7 on 2025-04-11 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewquestion',
            name='answer',
            field=models.TextField(blank=True),
        ),
    ]
